# Generated by Django 4.2.9 on 2024-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptmanagementsystem', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('prof', 'Professor'), ('stud', 'Student'), ('hod', 'Head of Department'), ('clerk', 'Clerk')], default='Student', max_length=10),
        ),
    ]
