# Generated by Django 4.2.9 on 2024-04-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deptmanagementsystem', '0004_forum_content_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='cgp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='deptmanagementsystem.student'),
            preserve_default=False,
        ),
    ]
