# Generated by Django 4.2.9 on 2024-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptmanagementsystem', '0005_remove_marks_marks_marks_cgp_marks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batchId',
            field=models.IntegerField(null=True),
        ),
    ]
