# Generated by Django 4.2.9 on 2024-04-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deptmanagementsystem', '0006_alter_student_batchid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
