# Generated by Django 4.2.9 on 2024-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptmanagementsystem', '0007_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
